### ISSUE TITLE
Setting local IP octets as subdomains in Cloudflare

### ISSUE THREAD

**Issue by begna112** [containeroo/SyncFlaer#103]
```
time="2022-02-15T08:26:36Z" level=error msg="Unable to create DNS record 172.16: HTTP status 400: An A, AAAA, or CNAME record with that host already exists. (81053)"
time="2022-02-15T08:26:37Z" level=error msg="Unable to create DNS record 192.168: HTTP status 400: An A, AAAA, or CNAME record with that host already exists. (81053)"
time="2022-02-15T08:26:37Z" level=info msg="Waiting 4 more runs until DNS record 172.16.example.com gets deleted"
time="2022-02-15T08:26:37Z" level=info msg="Waiting 4 more runs until DNS record 192.168.example.com gets deleted"
```

While working on #102 I noticed that my syncflaer is constantly adding and deleting two record like the above, over and over again. 

This is in docker-compose environment. 

I suspect the issue might have to do with my unique Traefik label setup to get internal and external routers separate.
```
      - "traefik.http.routers.wiki-int.rule=Host(`wiki.$DOMAIN`) && (ClientIP(`172.16.0.0/12`) || ClientIP(`192.168.0.0/16`))"
      - "traefik.http.routers.wiki.rule=Host(`wiki.$DOMAIN`)"
```

The above is on a number of my docker images and that's the only place either `172.16` or `192.168` are ever mentioned in any config files anywhere.

**Comment by rxbn** [comment]
Thanks for catching this bug! I'm implementing a fix today.

**Comment by rxbn** [comment]
Did v5.4.1 resolve your issues?

**Comment by begna112** [comment]
It looks like it did, yes.
