### ISSUE TITLE
Update checker feature rate limited

### ISSUE THREAD

**Issue by begna112** [containeroo/SyncFlaer#141]
```
time="2022-10-22T16:31:17Z" level=error msg="Failed to get latest release: GET https://api.github.com/repos/containeroo/syncflaer/releases/latest: 403 API rate limit exceeded for #.#.#.#. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 13m06s]"
```

The most recent addition "update checker" is getting rate limited by github. As fas as I can tell, there's no means of adding GH auth to the syncflaer config to prevent these. 

Could either auth be added or the rate limit errors be swallowed?

**Comment by rxbn** [comment]
Hi @begna112 

Thanks for reaching out! We will be suppressing all errors from the GitHub API in the next release :)

In the meantime, you can configure SyncFlaer to skip the update check: https://github.com/containeroo/SyncFlaer/blob/master/configs/config.yml#L3

-- Robin

**Comment by begna112** [comment]
Thanks for the quick response. I'll keep and eye out.
