### ISSUE TITLE
External IP Service 404ing

### ISSUE THREAD

**Issue by begna112** [containeroo/SyncFlaer#142]
```
time="2022-10-25T12:34:01Z" level=error msg="Unable to get public ip from https://myip.is/ip/: http status code 404"
```

I also get 404 in a browser for this url. 

If I go to https://myip.is, it works, and their "API" page is https://4.myip.is

Did the endpoint change? Should multiple options be defined in case one goes down?

**Comment by rxbn** [comment]
Hi @begna112 

You are right. It looks like the endpoint changed. Thanks for the heads-up!
I will remove myip.is from the defaults in the next release.

However, it should not affect SyncFlaer since it will just select another IP provider if one fails.

-- Robin
