### ISSUE TITLE
How do you only update subdomain zones, and not the main zone?

### ISSUE THREAD

**Issue by evulhotdog** [containeroo/SyncFlaer#89]
Hey there!

This tool is great! Thanks for writing it!

How do you only update subdomains and not the main domain zone? I've tried everything that I can think of and I can't find a way to do it in the config.

**Comment by rxbn** [comment]
Hey!

Thanks for your kind words :) Really appreciate it!

SyncFlaer currently manages the "root record" (example.com) to always be an A record pointing to your current public ip address. Disabling this feature is currently not possible.

However, if you can describe me why and for what reason you don't want to have your root record managed by SyncFlaer, I maybe can extended it :)

-- rxbn

**Comment by evulhotdog** [comment]
Thanks for the quick response!

I have a whole list of subdomains that I want to update the public IP's for, but, I don't want the main domain updated (or even set to anything, at all.)

This tool would be great for that use case but no matter what I am required to have that populated if I use this tool.

**Comment by rxbn** [comment]
Alright, thanks for the clarification!

Basically, I see two ways how we can handle this case:

1. Add an option to completely disable SyncFlaer to manage the root record
2. Add a configuration where users can define how their root record should look like (e.g. different record type, different ip than the current public ip, ...)

@gi8lino what is your opinion?

@evulhotdog would option 2 be something that fits your use case?

**Comment by evulhotdog** [comment]
Option 2 would be ideal, where setting record type to `None` would not modify it at all, or at least set it to what you want to set it to.

**Comment by gi8lino** [comment]
I think the nr 1 is easy to implement.
We can extend "additional records"  to also set the root domain, so we can cover nr 2 as well...

**Comment by evulhotdog** [comment]
> I think the nr 1 is easy to implement. We can extend "additional records" to also set the root domain, so we can cover nr 2 as well...

When I was brainstorming on how I would implement it, this is how I thought about it initially, just setting it there. Although you also shouldn't need to set the main domain, either?

**Comment by rxbn** [comment]
> When I was brainstorming on how I would implement it, this is how I thought about it initially, just setting it there. Although you also shouldn't need to set the main domain, either?

Exactly, this would also cause a breaking change if users suddenly have to define their root records by themself.

> I actually don't use my root :) It has no record at all.

Alright, now I understand it better :)


Let me see what I can do to fix your issue. I'll keep you posted!

**Comment by rxbn** [comment]
You can now update to v5.2.0. This version introduces a new config parameter: `managedRootRecord`. You can simply set it to `false` and SyncFlaer will delete your root record :)

Happy Holidays!

**Comment by xucian** [comment]
> and SyncFlaer will delete your root record

not sure if I follow. does this mean that I cannot use the root domain for other, unrelated services, because it can either be updated _or_ deleted? how about being left alone? 😁

**Comment by rxbn** [comment]
@xucian SyncFlaer is designed to manage your entire zone. You can use the `additionalRecords` config to set your root record to anything you want. Just make sure you set `managedRootRecord` to false.

**Comment by xucian** [comment]
Thanks!
Can I set a constant ip then for the root? it has to be the ip of another
machine

**Comment by rxbn** [comment]
@xucian Yes, you can:

```yaml
additionalRecords:
  - name: example.com
    proxied: true
    type: A
    contents: 1.1.1.1
```
